### ISSUE TITLE
Upgrading from 1.81.1 to 1.93.1 is causing OOMKilled events in cost-model container

### ISSUE THREAD

**Issue by jutley** [kubecost/cost-analyzer-helm-chart#1439]
**Describe the bug**

We previously ran cost-model in our test cluster with 6 GiB of memory. After upgrading from 1.81.1 to 1.91.1, we have increased the memory for this container up to 20 GiB, and it still crashes with an OOMKilled reason almost instantly. This container originally had 1 cpu, though we have increased this to 2 cpus. This doesn't seem to make any difference either.

**To Reproduce**
Not sure at this time.

**Expected behavior**
I would expect memory usage to be roughly the same, if not better after the upgrade. Certainly not OOMing with such high requests/limits.

**Logs**

Here are the logs before the crash:
```
///
2022-05-24T21:45:35.999405809Z INF ETL: Allocation[1h]: ETLStore[SYtpC]: build: completed [2022-05-23T16:00:00+0000, 2022-05-23T17:00:00+0000) from backup in 3.70201ms: coverage [2022-05-23T16:00:00+0000, 2022-05-24T21:45:35+0000) (60.7% complete)
2022-05-24T21:45:36.000175039Z INF ETL: Allocation[1h]: AggregatedStore[UQzsC]: run: aggregated [2022-05-23T16:00:00+0000, 2022-05-23T17:00:00+0000) from 178 to 76 in 505.868µs
2022-05-24T21:45:36.000766138Z INF ETL: Asset[1h]: ETLStore[fgdWH]: build: completed [2022-05-22T22:00:00+0000, 2022-05-22T23:00:00+0000) from backup in 1.702054ms: coverage [2022-05-22T22:00:00+0000, 2022-05-24T21:45:35+0000) (97.5% complete)
2022-05-24T21:45:36.000865641Z INF ETL: Asset[1h]: AggregatedStore.Run[kpbhq]: run: aggregated [2022-05-22T22:00:00+0000, 2022-05-22T23:00:00+0000) from 31 to 3 in 50.925µs
2022-05-24T21:45:36.002607639Z INF ETL: Allocation[1h]: ETLStore[SYtpC]: build: completed [2022-05-23T15:00:00+0000, 2022-05-23T16:00:00+0000) from backup in 3.16556ms: coverage [2022-05-23T15:00:00+0000, 2022-05-24T21:45:35+0000) (62.8% complete)
2022-05-24T21:45:36.002571417Z INF ETL: Asset[1h]: ETLStore[fgdWH]: build: completed [2022-05-22T21:00:00+0000, 2022-05-22T22:00:00+0000) from backup in 1.763251ms: coverage [2022-05-22T21:00:00+0000, 2022-05-24T21:45:35+0000) (99.5% complete)
2022-05-24T21:45:36.002697227Z INF ETL: Asset[1h]: ETLStore[fgdWH]: build: completed [2022-05-22T21:00:00+0000, 2022-05-24T21:45:35+0000) in 147.14863ms
```

gz#1870<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1870'>Zendesk ticket #1870</a>)</i>

**Comment by jutley** [comment]
I'm not familiar with the details around the data stored on the PV, but I did notice that starting with a fresh PV allowed the container to start successfully.

**Comment by AjayTripathy** [comment]
Hi @jutley sorry you're experiencing this. The PV holds our cache of historical data, so wiping this means we aren't serving historical data. You might try instead reading historical data out of the PV on-demand instead of caching it in memory by setting `Values.kubecostModel.etlFileStoreEnabled: true`

**Comment by jutley** [comment]
We've already addressed this in all our clusters by wiping out the persistent storage, so sadly I can't test this suggestion. I'm not sure whether you would prefer to keep this ticket open or not, so I'll close it and you can reopen if you think it is worth doing anything with.

**Comment by AjayTripathy** [comment]
Sure @jutley -- would just note that your data should still be rebuildable up to the retention period of your backing PromQL deployment. Here's a doc about how to get that data back: https://guide.kubecost.com/hc/en-us/articles/4407595942679-Kubecost-Diagnostics

**Comment by rlees85** [comment]
Fairly sure this should be open.

`Values.kubecostModel.etlFileStoreEnabled: true` is default to true in the Helm chart and the issue still persists.

The cost analyzer was sitting nicely at around 1.8GB memory usage until one day the deployment had to be restarted. Then the memory usage is spiking to 5 or 6GB plus and even giving it an unlimited amount it never settles back down. The logs spam the same messages over and over.

```
4
[90m2022-06-24T08:15:54.73423334Z[0m [32mINF[0m ETL: Allocation[1h]: AggregatedStore[laGQt]: run: aggregated [2022-06-24T03:00:00+0000, 2022-06-24T04:00:00+0000) from 191 to 58 in 739.261µs
93
[90m2022-06-24T08:15:55.505378088Z[0m [32mINF[0m ETL: Allocation[1h]: AggregatedStore[laGQt]: run: aggregated [2022-06-24T04:00:00+0000, 2022-06-24T05:00:00+0000) from 174 to 57 in 657.555µs
92
[90m2022-06-24T08:15:56.167719914Z[0m [32mINF[0m ETL: Allocation[1h]: AggregatedStore[laGQt]: run: aggregated [2022-06-24T05:00:00+0000, 2022-06-24T06:00:00+0000) from 158 to 57 in 612.151µs
91
[90m2022-06-24T08:15:56.765057749Z[0m [32mINF[0m ETL: Allocation[1h]: AggregatedStore[laGQt]: run: aggregated [2022-06-24T06:00:00+0000, 2022-06-24T07:00:00+0000) from 158 to 57 in 582.549µs
90
[90m2022-06-24T08:15:57.497557093Z[0m [32mINF[0m ETL: Allocation[1h]: AggregatedStore[laGQt]: run: aggregated [2022-06-24T07:00:00+0000, 2022-06-24T08:00:00+0000) from 158 to 57 in 681.057µs
89
[90m2022-06-24T08:15:58.053842224Z[0m [32mINF[0m ETL: Allocation[1h]: AggregatedStore[laGQt]: run: aggregated [2022-06-24T08:00:00+0000, 2022-06-24T09:00:00+0000) from 158 to 57 in 1.008284ms
88
[90m2022-06-24T08:18:20.511500426Z[0m [32mINF[0m ETL: Asset[1h]: AggregatedStore.Run[EJBWd]: run: aggregated [2022-06-24T02:00:00+0000, 2022-06-24T03:00:00+0000) from 29 to 3 in 118.309µs
87
[90m2022-06-24T08:18:21.018055833Z[0m [32mINF[0m ETL: Asset[1h]: AggregatedStore.Run[EJBWd]: run: aggregated [2022-06-24T03:00:00+0000, 2022-06-24T04:00:00+0000) from 33 to 3 in 206.917µs
86
[90m2022-06-24T08:18:21.381519173Z[0m [32mINF[0m ETL: Asset[1h]: AggregatedStore.Run[EJBWd]: run: aggregated [2022-06-24T04:00:00+0000, 2022-06-24T05:00:00+0000) from 31 to 3 in 150.413µs
85
[90m2022-06-24T08:18:21.736847539Z[0m [32mINF[0m ETL: Asset[1h]: AggregatedStore.Run[EJBWd]: run: aggregated [2022-06-24T05:00:00+0000, 2022-06-24T06:00:00+0000) from 29 to 3 in 161.313µs
84
[90m2022-06-24T08:18:21.819786317Z[0m [32mINF[0m ETL: Asset[1h]: AggregatedStore.Run[EJBWd]: run: aggregated [2022-06-24T06:00:00+0000, 2022-06-24T07:00:00+0000) from 0 to 0 in 1.1µs
83
[90m2022-06-24T08:18:21.896019539Z[0m [32mINF[0m ETL: Asset[1h]: AggregatedStore.Run[EJBWd]: run: aggregated [2022-06-24T07:00:00+0000, 2022-06-24T08:00:00+0000) from 0 to 0 in 1.201µs
82
[90m2022-06-24T08:18:22.070207583Z[0m [32mINF[0m ETL: Asset[1h]: AggregatedStore.Run[EJBWd]: run: aggregated [2022-06-24T08:00:00+0000, 2022-06-24T09:00:00+0000) from 0 to 0 in 1.7µs
```

I can wipe out the PV but seems utterly broken if we have to do that every time.....

`warmSavingsCache` made no difference (setting to false)
Reducing `etlDailyStoreDurationDays` made no difference either.

**Comment by AjayTripathy** [comment]
Hi @rlees85 can you share what version of kubecost you're running as well as a heap dump? https://guide.kubecost.com/hc/en-us/articles/4407595921431-Kubecost-Memory-Usage

**Comment by rlees85** [comment]
Version 1.94.3 which was broken. Rolling back to 1.92.0 resolved the issue. Clearing the persistent disk made no difference in our case.

When I can I will try and get a heap dump of 1.94.3

**Comment by AjayTripathy** [comment]
Thanks @rlees85 a heap dump of 1.92.0 vs 1.94.3 would be really useful in helping us debug this.
