### ISSUE TITLE
Advanced report asset breakdown include Kubernetes for __unallocated__

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1782]
**Describe the bug**

When trying to analyze external cost allocation, I noticed there is a line item for the `__unallocated__` external breakdown for "Kubernetes". Primarily looking for an explanation as to what this would be referring to, as all of the Assets marked with the "Kubernetes" service type are generally metrics directly from Kubecost.

**To Reproduce**

1. Configure an advanced report with the setting "Cloud Asset Data: Service"
1. Expand "\_\_unallocated__" dropdown.
1. See "Kubernetes" line item.

**Expected behavior**

All allocation line items that are related to metrics gathered by Kubecost should have aggregation parameters assigned so that they don't appear as \_\_unallocated__.

**Screenshots**

[Test Cluster](http://a33fe579340b346b6a7badbaa503699d-79357105.us-east-2.elb.amazonaws.com:9090/)
Test Configuration:
![](https://user-images.githubusercontent.com/43491549/199816520-68cda931-70ee-4cc1-94ef-e5093cc44970.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-206) by [Unito](https://www.unito.io)

**Comment by keithhand** [comment]
@dwbrown2, I'm not sure this is actually the case. From what I understand, all of the objects that are tagged with the "Kubernetes" service label should be coming directly from metrics that Kubecost gathers. Anything that is coming from a cost and usage report should have a "cloud-like" service attached to it (EC2, Cloud Storage, Microsoft.Compute, etc.).

**Comment by cr-benchmarkcorp** [comment]
A very large Enterprise Customer I am working with needs to aggregate costs at the Kubernetes Cluster level, for Cost Recovery purposes.   This capability (imo) should be 'out-of-the-box' functionality for KubeCost.    This is not happening on Azure and leads to ambiguity and multiple line items in report views.   I would recommend this issue be prioritized at a very high level within KubeCost as it's a flagship feature, marketed by the current product.

**Comment by AjayTripathy** [comment]
Cc @teevans @nealormsbee -- you guys have a handle on this one for v1.99 and the new advanced reports page?

**Comment by teevans** [comment]
Looping in @nikovacevic because I'm fairly the first run at this api will not include this.

**Comment by AjayTripathy** [comment]
Given that we implemented the ability to do a  != filter a drill down here shouldn't be hard to support right?

**Comment by nikovacevic** [comment]
I'm still not sure I understand the original ask here. Seems to me that people are expecting all Kubernetes Assets to have a `kubernetes_cluster` label, which is not the case. Furthermore, the new Advanced Reports we're building (i.e. the Allocation External API) will not interact at all with the Assets API -- only the Cloud Costs API.

Happy to help further if I can, but I would need to understand with more clarity.

Here's what we plan to provide:
* Allocation data, aggregated by a field
* External (i.e. cloud cost) data, joined with the Allocation data on a field
* Sub-breakdown of external costs by a field -- including any "unallocated" data

Does that clear things up?

**Comment by cr-benchmarkcorp** [comment]
The desired user experience is to aggregate the TCO of Kubernetes at the Cluster level on Azure.
This does not seem possible today, in a single line item in KubeCost.

**Comment by keithhand** [comment]
The problem here is that the aggregations on the advanced report don't quite match up with what is seen on an allocation report today, causing some confusion.

For example, the following two screenshots got generated using a last 30 days [report](http://a33fe579340b346b6a7badbaa503699d-79357105.us-east-2.elb.amazonaws.com:9090/allocations?context=W10%3D&agg=cluster&window=30d), aggregated on "Cluster"

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/43491549/201434807-bc37e556-df34-4002-8053-6891611e7df6.png">

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/43491549/201434779-acd5f62c-74df-42d6-b6a6-6b413f647db4.png">

As you can see in the screenshot, when we are on the allocation report, all of the in-cluster assets get associated with the correct cluster tag. However, when looking at the advanced report, since we swap to explicitly looking for the `kubernetes_cluster` label, we end up with many assets being associated as "\_\_unallocated\_\_" instead of with their correct cluster label.

**Comment by teevans** [comment]
@keithhand - We've got an adjusted version of Advanced Reports going out for 1.99. Let's follow up with this after that release, and see what we can do.

**Comment by cr-benchmarkcorp** [comment]
Thank you for the update @teevans .    Was there some progress made on this issue in v1.99 or are you saying wait for v1.99 to drop and then this issue will be addressed in a future version?

**Comment by teevans** [comment]
@cr-benchmarkcorp - we're actually going to be taking a very different approach to Advanced Reporting come 1.99. Because of this, Azure support won't be completely supported for at least 1 to 2 more versions. Since this is still an Alpha release, we're not planning on investing any more resources into the current alpha version of Advanced Reporting. However, with the new approach, I think we'll be able to find a way to solve this problem for you!

**Comment by cr-benchmarkcorp** [comment]
Thank you @teevans .    Also casting my vote for Azure as a first class citizen.  ;)

**Comment by cr-benchmarkcorp** [comment]
Hello @teevans   It appears that even in the standard reports (not advanced/alpha) out of cluster items tagged with "kubernetes_cluster=<cluster-name>" don't aggregate properly with what KubeCost finds by default in the same cluster.

Should we be treating this as a separate bug request from that pov, or open a new request.   Please let us know.

<img width="1409" alt="Screen Shot 2022-11-24 at 7 23 04 PM" src="https://user-images.githubusercontent.com/86609082/203878238-f16c6973-7579-4b80-b66f-9c180b8df48e.png">

<img width="1426" alt="Screen Shot 2022-11-24 at 7 23 42 PM" src="https://user-images.githubusercontent.com/86609082/203878256-264ead3a-ba21-4581-9bdf-300884ea2a3f.png">

<img width="1402" alt="Screen Shot 2022-11-24 at 7 24 08 PM" src="https://user-images.githubusercontent.com/86609082/203878267-5b8633fe-71ab-4ff7-a37d-10720565c9b6.png">

**Comment by teevans** [comment]
@nikovacevic - Any thoughts here?

**Comment by nikovacevic** [comment]
This is a misunderstanding of what is being displayed. "Cluster" is not the same thing as the label "kubernetes_cluster". One is a property, the other is a label. Does that help, or can I share more?

**Comment by nikovacevic** [comment]
As an example, there's nothing stopping someone from taking a node that Kubecost has identified as belonging to cluster "cluster-one" and applying the label "kubernetes_cluster=cluster-two". That item would have:
```
Cluster: "cluster-one"
Label["kubernetes_cluster"]: "cluster_two"
```

**Comment by nikovacevic** [comment]
At the beginning of Q1 2023, we're looking at splitting the Assets experience into two experiences: Kubernetes Assets, and Cloud Costs. (Something like that -- details will likely change as we work through it.) This should clear up some of the confusion, because the `label["kubernetes_cluster"]=...` pattern was meant for Cloud Costs, as a way of associating them with Kubernetes Assets, which have a native `cluster` property. The fact that both of those experiences live in the same page today makes things unclear.

**Comment by cr-benchmarkcorp** [comment]
Thank you for the update.  Regardless of whether the internal implementation is a tag or a label, customers have the need to aggregate costs (both in cluster and out of cluster) by Cluster.   This is not possible today with the standard reports, or the advanced Alpha reports for Azure (imo).

**Comment by teevans** [comment]
CC: @dwbrown2 - Is this something you'd want Kai to look at and see where we have gaps?
