### ISSUE TITLE
Recommending requests from data: CPU algorithm set to max but no max data is available when setting filter label in savings > container right-sizing > customize

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#2104]
**Describe the bug**  
When entering a label example.acme.kubernetes.io/costcenter  in the savings page, we get the following 500 error:
`Recommending requests from data: CPU algorithm set to max but no max data is available`

This does not happen with ns'. 

**To Reproduce**  
1. Go to Savings > container right-sizing > customize
2. Set label equal to label. We tried the following which includes the recommended the format key:value 
a) example.acme.kubernetes.io/costcenter
b) example.acme.kubernetes.io:costcenter
c) costcenter

`Recommending requests from data: CPU algorithm set to max but no max data is available`

**Comment by dwbrown2** [comment]
@nealormsbee @teevans the only instance of this that I saw was resolved today... know if this still outstanding?

**Comment by AjayTripathy** [comment]
Have we been able to get a consistent repro here in 102.1 @mmurph3 ?

**Comment by mmurph3** [comment]
@AjayTripathy this was repro'd in v1.102.1 on call with customer this morning. I can add a video snippet to cost-analyzer-frontend repo and link this issue if that helps.

**Comment by kwombach12** [comment]
@mmurph3 That would be helpful - Thank you

**Comment by kirbsauce** [comment]
easily reproducible in 102.0 on demo cluster.

**Comment by AjayTripathy** [comment]
cc @teevans for triage.

**Comment by teevans** [comment]
@allyleonce - Can you get this on the burndown list plz

**Comment by AjayTripathy** [comment]
@michaelmdresser do you know what's going on here? Can you take a look?

**Comment by AjayTripathy** [comment]
@kirbsauce I'm hearing that this has been fixed in nightly. I'm not sure what cluster you were looking at it as broken on, but can you confirm/deny that it's working?

**Comment by kirbsauce** [comment]
@AjayTripathy the issue still seems to exist with at least pod and containerName.  

http://nightly.kubecost.io:9090/request-sizing?filter=W3sicHJvcGVydHkiOiJwb2QiLCJ2YWx1ZSI6IngiLCJlcXVhbGl0eSI6IjoifV0%3D&window=7d&page=0&itemsPerPage=10&algorithmCPU=max&algorithmRAM=max&qCPU=0.95&qRAM=0.95&targetCPUUtilization=0.8&targetRAMUtilization=0.8&profile=custom

**Comment by michaelmdresser** [comment]
@kirbsauce for the user, have you tried `example_acme_kubernetes_io_costcenter`? There is an unfortunate limitation with v2 filters right now around Prom sanitization. This is the underlying issue.

---

The 500 itself is occurring because there are no workloads matching the filter. Instead of returning a 200 and an empty response, the endpoint currently returns a 500 and the error described in this issue. I just opened a PR to return a 200 and empty response in this situation https://github.com/kubecost/kubecost-cost-model/pull/1409.

**Comment by kirbsauce** [comment]
@michaelmdresser.  this was simply something I was playing around with so no user involved.  @mmurph3 was actually working with a user.

**Comment by mmurph3** [comment]
@michaelmdresser steps we did with user:

1. The user applies filter  cost.example1.kubernetes.io/centercode in allocations page.
2. Then the user goes to savings page > Request right-sizing recommendations and adds the following filter: 
cost.example1.kubernetes.io/centercode:12345
3. We then get the 500 error: 
<img width="478" alt="image" src="https://user-images.githubusercontent.com/36980248/234594296-aceb04a6-48bc-4038-a0a6-a6aede26a87f.png">
4. We're also seeing commas for the percentages. They are using EUR currency (I cannot repro this when using that currency) 
<img width="299" alt="image" src="https://user-images.githubusercontent.com/36980248/234594622-99db81fc-f608-4173-8ad5-1d28ec730070.png">

**Comment by michaelmdresser** [comment]
@mmurph3 Has the user tried `cost_example1_kubernetes_io_centercode:12345` on the request right-sizing recommendation page?

**Comment by michaelmdresser** [comment]
Once we release v1.103 and the user upgrades, I'd like to see if this behavior remains the same for the user.

**Comment by rossfisherkc** [comment]
This issue is still occurring as of 1.104 @michaelmdresser cc @mmurph3 
```
Kubecost Info
Version
*1.104.1*
API Version
*1.104.1 (e83df77)*
License Version
*FREE*

*2) Single cluster*
*4)* $ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short. Use --output=yaml|json to get the full version.
Client Version: <http://version.Info|version.Info>{Major:"1", Minor:"25+", GitVersion:"v1.25.11-dispatcher", GitCommit:"bb1bff031c9872d3d4c0a97871ae1a8d4882950a", GitTreeState:"clean", BuildDate:"2023-06-28T15:04:49Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
```

![1fva81ljym5vnx-image-3](https://github.com/kubecost/cost-analyzer-helm-chart/assets/113053906/1054d500-55af-4705-9fb4-8b2749241696)

Case https://kubecost.zendesk.com/agent/tickets/4574

**Comment by A-Nabelsi** [comment]
Hello! The issue is above is occurring with me. I let the 24h hours pass thinking it didn't have enough data but I believe I might just have entered the config wrong.



I currently have the kubecost config in my values.yml, but all I added was:

```
  kubecostModel:
    containerStatsEnabled: true
    ###other configs
```
Here's the customization:
Note: I cannot lower the cpu percentile under 0.95 either
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/92064100/d625846a-d7ee-4b86-947c-99a7e6641133)


Sidenote:
It does not let me  change CPU percentile from 0.95 and whenever I try to change the RAM percentile it does not let me add periods, commas give NaN, so I end up having whole numbers which wont work of course.

![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/92064100/20be1c3a-732b-4b10-ad20-c49ab20ef059)

**Comment by A-Nabelsi** [comment]
Enabling works now it was a silly mistake on my part. Though I still cannot lower the CPU percentile under 0.95 which is still problematic... @michaelmdresser cc @mmurph3

**Comment by rossfisherkc** [comment]
@A-Nabelsi could you share what the fix was? I can help update our docs so it's more clear!

As for the percentile, I'll ensure this is taken care of

**Comment by A-Nabelsi** [comment]
The mistake for it not being enabled was mostly on my part, the docs were clear enough but essentially I was enabling it in the wrong helm configuration/wrong chart  and pushing my code to the wrong repo (and it wasn't working since it was unrelated to the kubecost deployment). The fix was as simple as writing the configuration in the right helm chart and repo (which contains kubecost's configurations for our deployment).

For the cpu percentile, I kept testing but I don't think it's a UI issue. the ram one I can change but it is still funky as mentioned above. The cpu one does not move no matter what I try, it stays at 0.95.

Thank you @rossfisherkc!

**Comment by rossfisherkc** [comment]
@michaelmdresser what specific info could I collect before opening a Jira issue for

@Ross Fisher I was able to enable the pipeline after all but discovered a bug related to CPU percentile, I cannot lower it at all, it won't budge from 0.95. The ram one can be lowered tho. I updated the github issue with the new info as well.

**Comment by A-Nabelsi** [comment]
@rossfisherkc It works now with the latest update!  I can change the CPU and ram percentile perfectly.

**Comment by rossfisherkc** [comment]
Closing as resolved!
