### ISSUE TITLE
Cloud Costs not working

### ISSUE THREAD

**Issue by metalbahamut** [kubecost/cost-analyzer-helm-chart#2205]
**Describe the bug**  
After enabling Azure Cloud Costs (with cloud-integration.json secret) it's not working and not showing anything in the web. Also seeing a lot of errors regarding "ERR Azure: failed to parse vmss number for VM %!s(<nil>): did not find number in provided string" but not sure if related.
It seems it works in version "prod-1.100.2" but failing in "prod-1.102.2".

**To Reproduce**  
To create the Azure storage account with daily exports reports.
To configure Kubecost with cloud-integration.json secret.

**Expected behavior**  
Cloud costs shown.

**Screenshots**  
![image](https://user-images.githubusercontent.com/70911101/235313151-eb9e8c6c-effc-425d-91d7-526772444f12.png)

**Collect logs (please complete the following information):**
[kubecost-cost-analyzer-6b6958dc98-z5zwz-cost-model.log](https://github.com/kubecost/cost-analyzer-helm-chart/files/11359631/kubecost-cost-analyzer-6b6958dc98-z5zwz-cost-model.log)

**Comment by kwombach12** [comment]
@thomasvn Could you take a look at the integration challenges here?

**Comment by thomasvn** [comment]
Hey @metalbahamut! If you go to the [/diagnostics](https://docs.kubecost.com/troubleshooting/diagnostics) view, could you share a screenshot of the “Cloud Integrations” section? Additionally, have you enabled the [Cloud Cost Explorer config](https://docs.kubecost.com/using-kubecost/navigating-the-kubecost-ui/cloud-costs-explorer) via Helm?

**Comment by jjarrett21** [comment]
I actually have a fix for this in PR  the API changed and we hadn't updated it for the front end


Update: this should be resolved in the latest RC

**Comment by djsly** [comment]
which RC ? I'm using rc11 and I still cannot get it to work :(

**Comment by kwombach12** [comment]
We are pushing out v1.103 today which should have the fix! Please let us know if you still face the issue after upgrading!

**Comment by djsly** [comment]
I got it working with rc.11. All set ! On May 4, 2023, at 3:24 PM, Kai Wombacher ***@***.***> wrote:﻿
We are pushing out v1.103 today which should have the fix! Please let us know if you still face the issue after upgrading!
