### ISSUE TITLE
[Bug]  Duplicated labels for networkCosts DaemonSet

### ISSUE THREAD

**Issue by k7k0** [kubecost/cost-analyzer-helm-chart#2737]
### Kubecost Helm Chart Version

1.107.0

### Kubernetes Version

1.26.9

### Kubernetes Platform

EKS

### Description

The existing [network cost DaemonSet definition](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.107.0/cost-analyzer/templates/cost-analyzer-network-costs-template.yaml#L8-L12) is duplicating the `app.kubernetes.io/instance` and `app.kubernetes.io/name` labels by appending the `.Values.networkCosts.additionalLabels` values.

As these additional labels are [defaulted to non-empty values](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.107.0/cost-analyzer/values.yaml#L899-L901), there is no way to remove the values from the map during the chart instantiation.

### Steps to reproduce

1. Render the existing chart using default values and setting `networkCosts.enabled:  true`
2. Search for generated manifest looking for `kind: DaemonSet`
3. Check duplicated labels:

```
  labels:
    app.kubernetes.io/name: cost-analyzer
    helm.sh/chart: cost-analyzer-1.107.0
    app.kubernetes.io/instance: kubecost
    app.kubernetes.io/managed-by: Helm
    app: cost-analyzer
    app.kubernetes.io/instance: kubecost
    app.kubernetes.io/name: network-costs
```

### Expected behavior

Generated labels should be unique

### Impact

Label duplication is a bad practice and also breaks some tools like `kustomize`, for example
```
    line 14: mapping key "app.kubernetes.io/name" already defined at line 8
    line 13: mapping key "app.kubernetes.io/instance" already defined at line 10]
```

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by k7k0** [comment]
bug was introduced as part of https://github.com/kubecost/cost-analyzer-helm-chart/pull/2677

**Comment by dwbrown2** [comment]
cc @jessegoodier any chance you could take a look when you have time?

**Comment by jessegoodier** [comment]
> bug was introduced as part of #2677

Thanks for the detail. I'm still looking at the best fix for this. Likely will drop the common labels.

for now, you can remove the additional labels with:

```yaml
networkCosts:
  additionalLabels: null
```

which should fix the install, if you could confirm?

**Comment by k7k0** [comment]
Thanks for the quick replies! I tried the approach, but it didn't work, probably as we're wrapping the cost-analyzer chart this way:
```yaml
# Chart.yaml
apiVersion: v2
name: kubecost-wrapper
version: 0.1.0
description: 'Wrapper chart for kubecost'
dependencies:
  - name: cost-analyzer
    version: 1.107.0
    repository: https://kubecost.github.io/cost-analyzer
``` 

```yaml
# values.yaml
cost-analyzer:
  networkCosts:
    enabled: true
    additionalLabels: null
```

When I template the chart, I still get the duplicated labels.

**Comment by jessegoodier** [comment]
> Thanks for the quick replies! I tried the approach, but it didn't work, probably as we're wrapping the cost-analyzer chart this way:
> 
> ```yaml
> # Chart.yaml
> apiVersion: v2
> name: kubecost-wrapper
> version: 0.1.0
> description: 'Wrapper chart for kubecost'
> dependencies:
>   - name: cost-analyzer
>     version: 1.107.0
>     repository: https://kubecost.github.io/cost-analyzer
> ```
> 
> ```yaml
> # values.yaml
> cost-analyzer:
>   networkCosts:
>     enabled: true
>     additionalLabels: null
> ```
> 
> When I template the chart, I still get the duplicated labels.

Thanks, I was curious what your process was because you're the first report of this. I do see the duplicates when I template the chart, but it doesn't include the commonLabels when installing via helm.

I can create a one-off helm package if you want to test the proposed change, just let me know.

We will most likely have a patch out early next week.

**Comment by jessegoodier** [comment]
FYI for all:
This #2734 should prevent issues like this in the future. Thanks @chipzoller !
