### ISSUE TITLE
Grafana dashboards imported the sidecar with an hardcoded datasource.

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cost-analyzer-helm-chart#744]
**Describe the bug**
All the dashboards imported by the sidecar are using `"datasource": "default-kubecost"`.

If you use a custom installation of Grafana and Prometheus, the dashboards cannot be used.

**To Reproduce**
Install kubecost with a custom Prometheus and Grafana installation and name the Prometheus datasource with something other than `default-kubecost`.

**Expected behavior**
Being able to use dashboards in a custom installation.

There are two possibilities:
1) give the possibility to configure the name of the datasource in the chart
2) create more general dashboards (best choice)

Tip for the second option: change the datasource in the dashboard in this way `"datasource": "${DS_PROMETHEUS}"` and add a dropdown list in the templating part like:

```
"templating": {
    "list": [
      {
        "current": {
          "selected": false,
          "text": "",
          "value": ""
        },
        "error": null,
        "hide": 0,
        "includeAll": false,
        "label": null,
        "multi": false,
        "name": "DS_PROMETHEUS",
        "options": [],
        "query": "prometheus",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "type": "datasource"
      }
   }
}
```

**Comment by AjayTripathy** [comment]
Hi @pierluigilenoci there are legacy reasons we do this. We're open to implementing a set of dashboards that use the DS_PROMETHEUS templating, but is a workaround for now just to create a datasource that is called "default-kubecost" in your grafana dashboard?

**Comment by pierluigilenoci** [comment]
I've already used this workaround for my PoC with Kubecost but it still remains a dirty trick to get things working.

In my specific case, however, it is not sufficient because I have a single Grafana installation to which all Prometheus installations are connected as datasource. So only one works at a time.

As I said in another ticket, in my opinion, the chart should reward those who update their software compared to those who run legacy versions. In any case, forcing the usage of external workarounds and dirty tricks to make things work does not give a good product image. 

Ref: https://github.com/kubecost/cost-analyzer-helm-chart/issues/747#issuecomment-770383226

**Comment by pierluigilenoci** [comment]
@AjayTripathy any update?

**Comment by dwbrown2** [comment]
@Sean-Holcomb were you going to look at this?

**Comment by Sean-Holcomb** [comment]
I have updated all of our Grafana templates to include the datasource dropdown that was suggested above. This should be available in the release going out tomorrow.

**Comment by dwbrown2** [comment]
Fixed in v1.76! Thanks, @Sean-Holcomb.

Let us know if we can get you anything else on this!

**Comment by pierluigilenoci** [comment]
In reality, this is not completely resolved. Now if you have more than one datasource from different Kubecost installations, the dashboard that is opened from the links of the Kubecost UI does not pull up the right datasource that needs to be adjusted by hand. The correct datasource name should be added in the installation and then the parameter added in the ui in this way: `&var-datasource=mycustomdatasource`

**Comment by pierluigilenoci** [comment]
I created this issue as follow up https://github.com/kubecost/cost-analyzer-helm-chart/issues/817
