### ISSUE TITLE
Azure Out of Cluster Costs don't work with export

### ISSUE THREAD

**Issue by sylus** [kubecost/cost-analyzer-helm-chart#917]
Hi there!

It seems that the kubecost out of cluster costs don't work for us and it is looking for mappings that don't exist in our export.

We are greeted with numerous errors related to parsing of the CSV:

```
E0527 19:04:03.056562 1 log.go:17] [Error] failed to parse usage date: 'Statcan'
E0527 19:04:03.056573 1 log.go:17] [Error] failed to parse usage date: 'Statcan'
E0527 19:04:03.056578 1 log.go:17] [Error] failed to parse usage date: 'Statcan'
E0527 19:04:03.056585 1 log.go:17] [Error] failed to parse usage date: 'Statcan'
E0527 19:04:03.056595 1 log.go:17] [Error] failed to parse usage date: 'Statcan'
E0527 19:04:03.056601 1 log.go:17] [Error] failed to parse usage date: 'Statcan'
E0527 19:04:03.056613 1 log.go:17] [Error] failed to parse usage date: 'Statcan'
E0527 19:04:03.056621 1 log.go:17] [Error] failed to parse usage date: 'Statcan'
```

It seems you are looking for `UsageDateTime` and our CSV export from Azure doesn't have that value. It also seems that the date format is also incorrect. I have attached the first header line of our logs to show the problem.

```
InvoiceSectionName,AccountName,AccountOwnerId,SubscriptionId,SubscriptionName,ResourceGroup,ResourceLocation,Date,ProductName,MeterCategory,MeterSubCategory,MeterId,MeterName,MeterRegion,UnitOfMeasure,Quantity,EffectivePrice,CostInBillingCurrency,CostCenter,ConsumedService,ResourceId,Tags,OfferId,AdditionalInfo,ServiceInfo1,ServiceInfo2,ResourceName,ReservationId,ReservationName,UnitPrice,ProductOrderId,ProductOrderName,Term,PublisherType,PublisherName,ChargeType,Frequency,PricingModel,AvailabilityZone,BillingAccountId,BillingAccountName,BillingCurrencyCode,BillingPeriodStartDate,BillingPeriodEndDate,BillingProfileId,BillingProfileName,InvoiceSectionId,IsAzureCreditEligible,PartNumber,PayGPrice,PlanName,ServiceFamily,CostAllocationRuleName
```

One note when i do try to manually fix the header field I then hit the date issue:

````
E0528 00:11:30.624577 1 log.go:17] [Error] failed to parse usage date: '05/22/2021'
E0528 00:11:30.624584 1 log.go:17] [Error] failed to parse usage date: '05/13/2021'
E0528 00:11:30.624595 1 log.go:17] [Error] failed to parse usage date: '05/14/2021'
E0528 00:11:30.624600 1 log.go:17] [Error] failed to parse usage date: '05/21/2021'
E0528 00:11:30.624605 1 log.go:17] [Error] failed to parse usage date: '05/21/2021'
```

Note we also don't have a PreTaxCost field that is next to fail.

**Comment by dwbrown2** [comment]
Adding @Sean-Holcomb as the owner of this system! I know he has an active thread with the Azure team on a related issue that they are investigating. I'll let him share more.

**Comment by Sean-Holcomb** [comment]
@sylus I appreciate the feedback, I actually a have fix for this issue that will be going out in a release candidate build that is expected that we will have next week. I will keep you updated when that is out.

**Comment by sylus** [comment]
Awesome @Sean-Holcomb I really need this functionality so keenly waiting for release :D

**Comment by Sean-Holcomb** [comment]
@sylus Changes are still in the pipeline, will let you know right away when I have more updates.

**Comment by Sean-Holcomb** [comment]
@sylus We have some updates for this issue going into the nightly build tonight, you can grab that using these [instructions](https://github.com/kubecost/docs/blob/master/release-process.md#nightly-releases). 

Please let me know if you run into any issues with it and I will hopefully be able to get you a fix much quicker in another nightly build now that the bulk of the changes are in place.

**Comment by dwbrown2** [comment]
@sylus just wanted to see if this correctly handled your different billing data format. Just let us know if we can get you anything else!

**Comment by sylus** [comment]
Hi there @dwbrown2 sadly I don't think it works but maybe some of the following logs might help cause I do see logs of it correctly grabbing the file to parse.

Currently I only see Kubernetes, Disks and LB’s in my cost allocation.

Before when I manually adjusted the CSV I was able to see Azure Managed DB for PostgreSQL.

```
I0615 00:08:23.449679       1 log.go:47] [Info] Azure Storage: retrieving blob: exports/aaw/20210601-20210630/aaw_XXXXX.csv
E0615 00:08:23.472832       1 log.go:17] [Error] ETL: Asset[1d]: Reconciliation[UmYEP]: error: ReconcileAssets: AssetSetRange is empty for [2021-06-02T00:00:00+0000, 2021-06-09T00:00:00+0000)
I0615 00:08:23.473012       1 log.go:47] [Info] Azure Storage: retrieving most recent reports from: 2021-05-26 00:00:00 +0000 +0000 - 2021-06-02 00:00:00 +0000 +0000
I0615 00:08:23.478003       1 log.go:47] [Info] Azure Storage: retrieving blob: exports/aaw/20210601-20210630/aaw_2XXXXX.csv
I0615 00:08:23.597756       1 clustersizing.go:198] error: recommend machines: single pool strategy: Get "https://prices.azure.com/api/retail/prices?$filter=serviceName%20eq%20%27Virtual%20Machines%27%20and%20serviceFamily%20eq%20%27Compute%27%20and%20priceType%20eq%20%27Consumption%27%20and%20armRegionName%20eq%20%27westus2%27": EOF
I0615 00:08:23.648864       1 clustersizing.go:208] error: recommend machines: multi-pool strategy: Get "https://prices.azure.com/api/retail/prices?$filter=serviceName%20eq%20%27Virtual%20Machines%27%20and%20serviceFamily%20eq%20%27Compute%27%20and%20priceType%20eq%20%27Consumption%27%20and%20armRegionName%20eq%20%27westus2%27": EOF
```

Also some of the following:

```
I0615 00:20:20.325082 1 log.go:62] [Profiler] 3.993693ms: ExternalAllocations: [2021-06-15T00:00:00+0000, 2021-06-16T00:00:00+0000)
I0615 00:20:20.326967 1 log.go:32] [Warning] AllocationSet.AggregateBy: error getting share coefficienct for 'cluster-one/__idle__'
I0615 00:20:20.326995 1 log.go:32] [Warning] AllocationSet.AggregateBy: error getting share coefficienct for 'cluster-one/__idle__'
I0615 00:20:20.327004 1 log.go:32] [Warning] AllocationSet.AggregateBy: error getting share coefficienct for 'cluster-one/__idle__'
I0615 00:20:20.327012 1 log.go:32] [Warning] AllocationSet.AggregateBy: error getting share coefficienct for 'cluster-one/__idle__'
```

**Comment by Sean-Holcomb** [comment]
@sylus just to clarify you are seeing Disks and LBs in the asset view but not your managed db?

**Comment by sylus** [comment]
That is correct @Sean-Holcomb  :D

**Comment by Sean-Holcomb** [comment]
Great well that is some progress, it sounds like some OOC costs are being added in, can you also confirm if you are seeing any values appear in the adjustments column for your in-cluster costs or any network category items under the kubernetes service?

What exactly did you update in your CSVs was it just the date format and the headers of the columns? Can you share some of the tags of that particular row? Is there a "creationSource" tag?

**Comment by sylus** [comment]
Unfortunately I am not seeing any of that and last I remember I had to adjust the date header, as well as the whole date column to be in a format it expected as well as some billing related rows that weren't mapping.

Here is the header for my CSV that I am trying to parse in its original state:

```sh
InvoiceSectionName,AccountName,AccountOwnerId,SubscriptionId,SubscriptionName,ResourceGroup,ResourceLocation,Date,ProductName,MeterCategory,MeterSubCategory,MeterId,MeterName,MeterRegion,UnitOfMeasure,Quantity,EffectivePrice,CostInBillingCurrency,CostCenter,ConsumedService,ResourceId,Tags,OfferId,AdditionalInfo,ServiceInfo1,ServiceInfo2,ResourceName,ReservationId,ReservationName,UnitPrice,ProductOrderId,ProductOrderName,Term,PublisherType,PublisherName,ChargeType,Frequency,PricingModel,AvailabilityZone,BillingAccountId,BillingAccountName,BillingCurrencyCode,BillingPeriodStartDate,BillingPeriodEndDate,BillingProfileId,BillingProfileName,InvoiceSectionId,IsAzureCreditEligible,PartNumber,PayGPrice,PlanName,ServiceFamily,CostAllocationRuleName
```

**Comment by Sean-Holcomb** [comment]
That is strange, are you seeing any errors along the lines of "AzureCSVLineParser: missing index for parse key" or "failed to parse..." or "Could not parse..."

**Comment by sylus** [comment]
Nope nothing other then the errors i posted above, probably unrelated but when I click on Asssets -> Kubernetes -> Node I then get a white screen. 

Seems to be a JS Error "Cannot read property start of undefined" instrument.ts for rangechart.

**Comment by sylus** [comment]
I do see this:

```
I0615 12:08:27.637481 1 log.go:47] [Info] Azure Storage: retrieving most recent reports from: 2021-06-09 00:00:00 +0000 +0000 - 2021-06-16 00:00:00 +0000 +0000
I0615 12:08:27.643760 1 log.go:47] [Info] Azure Storage: retrieving blob: exports/aaw/20210601-20210630/aaw_XXXXXX.csv
E0615 12:08:27.884722 1 log.go:17] [Error] ETL: Asset[1d]: Reconciliation[UmYEP]: error: ReconcileAssets: AssetSetRange is empty for [2021-06-09T00:00:00+0000, 2021-06-16T00:00:00+0000)
```

**Comment by Sean-Holcomb** [comment]
The JS issue is interesting, do you see anything in the network tab of that page that seems different, maybe a failed requests or an empty response?

If you haven't already can you try a rebuild of the asset etl using this endpoint `/model/etl/asset/rebuild?commit=true`
and let me know if you are just seeing the same kind of error messages

**Comment by sylus** [comment]
I tried the etl reload and still no go but I can see it looks like successfully parsed as can see the percentage increment.

The network error I am getting is (429 Too Many Requests)

```
https://o394722.ingest.sentry.io/api/5477757/store/?sentry_key=23f9f6e81ea14c8c8d40788f56c40abc&sentry_version=7
```

```
{"detail":"failed to read request body","causes":["failed to decode zlib payload","corrupt deflate stream"]}
```

**Comment by sylus** [comment]
I am still wondering about these errors:

```
I0615 19:17:31.564804 1 log.go:62] [Profiler] 23.446345ms: ExternalAllocations: [2021-06-09T00:00:00+0000, 2021-06-16T00:00:00+0000)
I0615 19:17:31.564962 1 log.go:32] [Warning] ETL: invalid values for shared coefficients: %!d(float64=0), %!d(float64=46.51286652583645)
I0615 19:17:31.565461 1 log.go:32] [Warning] AllocationSet.AggregateBy: error getting share coefficienct for 'cluster-one/__idle__'
I0615 19:17:31.565471 1 log.go:32] [Warning] AllocationSet.AggregateBy: error getting share coefficienct for 'cluster-one/__idle__'
I0615 19:17:31.565474 1 log.go:32] [Warning] AllocationSet.AggregateBy: error getting share coefficienct for 'cluster-one/__idle__'
I0615 19:17:31.565478 1 log.go:32] [Warning] AllocationSet.AggregateBy: error getting share coefficienct for 'cluster-one/__idle__'
```

**Comment by Sean-Holcomb** [comment]
So the percentage is Kubecost building the assets from the Prometheus data, the CSV parsing should happen after it gets to 100%. Are the disks and LB still there after the rebuild? 

I don't think that those errors are related to the issue at hand, but they are generated at query time on the Allocations page. If you navigate around that page with these  with idle cost set to separate do the errors still happen. If it is already set to separate can you try idle by cluster setting and see if they persist? I am not sure if they are a downstream consequence of the parsing issue yet, but that might be the case.
![Screen Shot 2021-06-15 at 1 00 15 PM](https://user-images.githubusercontent.com/12225425/122116111-168f8080-cdda-11eb-8ae2-5cee43dedfa7.png)

**Comment by Sean-Holcomb** [comment]
In terms of the network error it is caused by the JS error that you are seeing. I would be interested to see some of the results of the assets api when you see that error. particularly it sounds like there is an asset that is missing its start value.

**Comment by sylus** [comment]
Actually I had a question is the cost model code in master branch the latest? 

In my OP at the top I mentioned we don't have a `UsageDateTime` and only a `Date` field and also our format is of '06/14/2021' which based on the cost model is not what you detecting for?

I might be wholly wrong but just want to rule this out before go further.

**Comment by Sean-Holcomb** [comment]
Yeah so the update I put out in our closed source repo addresses that part of the issue. I am somewhat confident that that is no long the issue because you are no longer seeing those parse errors
`E0527 19:04:03.056562 1 log.go:17] [Error] failed to parse usage date: 'Statcan'`
It is now parsing the CSV for the "Date" column and is using the formate "01/02/2006" which is "MM/DD/YYYY"

**Comment by sylus** [comment]
Hmm I did that fix renamed Date to UsageDateTime and now I see this in error:

```
I0616 01:38:11.712582 1 log.go:32] [Warning] AzureCSVLineParser: missing index for parse key
I0616 01:38:11.712597 1 log.go:32] [Warning] AzureCSVLineParser: missing index for parse key
I0616 01:38:11.712695 1 log.go:32] [Warning] AzureCSVLineParser: missing index for parse key
I0616 01:38:11.712709 1 log.go:32] [Warning] AzureCSVLineParser: missing index for parse key
E0616 01:38:11.712715 1 log.go:17] [Error] failed to parse cost: ''
I0616 01:38:11.712730 1 log.go:32] [Warning] AzureCSVLineParser: missing index for parse key
I0616 01:38:11.712737 1 log.go:47] [Info] AzureCSVLineParser: missing index for parse key logged 5 times: suppressing future logs
E0616 01:38:11.712761 1 log.go:17] [Error] failed to parse cost: ''
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a1b16d]

goroutine 157 [running]:
github.com/kubecost/kubecost-cost-model/pkg/provider.(*Azure).parseCSVForASR(0xc009cf9c20, 0xc0005fe1b0, 0x0, 0xed8534d00, 0xc009d0ec40, 0x0, 0xed85c8780, 0xc009d0ec40, 0x4e94914f0000, 0xc0042a1a20, ...)
/app/kubecost-cost-model/pkg/provider/azure.go:107 +0x76d
github.com/kubecost/kubecost-cost-model/pkg/provider.(*Azure).csvToAssetSetRange(0xc009cf9c20, 0xc009d6a4e0, 0xc009d6a4f8, 0x4e94914f0000, 0x22b9380, 0x2fc7158, 0x1f61ae0, 0xc009d58d01, 0xc009d6a4f8)
/app/kubecost-cost-model/pkg/provider/azure.go:58 +0x1c5
github.com/kubecost/kubecost-cost-model/pkg/provider.(*Azure).QueryAssetSetRange(0xc009cf9c20, 0xc009d6a4e0, 0xc009d6a4f8, 0x4e94914f0000, 0xc009ea62f0, 0xc0003bb938, 0xc0020eab40)
/app/kubecost-cost-model/pkg/provider/azure.go:48 +0x6f
main.(*ETL).ReconcileAssets(0xc00ab81720, 0x0, 0xed8534d00, 0xc009d0ec40, 0x0, 0xed85c8780, 0xc009d0ec40, 0x4e94914f0000, 0x0, 0x1)
/app/kubecost-cost-model/etl.go:902 +0xf0
main.(*ETL).RunAssetReconciliation.func1(0xc00ab81720, 0xc00bf341d0, 0x5, 0xc00bf38000)
/app/kubecost-cost-model/etl.go:859 +0x836
created by main.(*ETL).RunAssetReconciliation
/app/kubecost-cost-model/etl.go:818 +0xc5
```

**Comment by sylus** [comment]
Yup and replacing EffectivePrice with PreTaxCost i start to see entries for KeyVault and Azure PostgreSQL etc. (I wasnt sure if i replace EffectivePrice or CostInBillingCurrency)

**Comment by Sean-Holcomb** [comment]
Ok that is more likely part of the issue, I was looking for the `CostInBillingCurrency`. I will switch it with `EffectivePrice`. Out of Curiosity is CostInBillingCurrency empty on you CSV?

**Comment by Sean-Holcomb** [comment]
I just merged the update, so it should be in our nightly build tonight if you want to give it another try tomorrow

**Comment by sylus** [comment]
@Sean-Holcomb so you merged both the date fix and the cost one? Only with the date fix did it even start to parse it looks like.

And yup both have had values in them.

**Comment by sylus** [comment]
Also might you know why i keep getting white screens on a page that loads successfully? After a few seconds and the page loading it will then white screen and I get this:

![image](https://user-images.githubusercontent.com/984304/122216116-04651f00-ce7a-11eb-8210-6a503b63a577.png)

**Comment by sylus** [comment]
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/984304/122229060-6d529400-ce86-11eb-949b-c813f42f1db4.png)

**Comment by AjayTripathy** [comment]
Hi @sylus that screen is a result of a bug in our release candidate/nightlies, we will have a fix there available soon.

**Comment by Sean-Holcomb** [comment]
Was able to find another bug with the parsing of the "Date" header this morning. It will be in tonights nightly build.

Let's try again tomorrow morning. As always, I really appreciate your feedback here, it really is invaluable.

**Comment by sylus** [comment]
Awesome thanks so much @AjayTripathy  let me know and i can try it out :D

**Comment by Sean-Holcomb** [comment]
You can grab the nightly release using these instructions https://github.com/kubecost/docs/blob/master/release-process.md#nightly-releases

**Comment by sylus** [comment]
Hi @Sean-Holcomb so it does seem to work which is great!

I do still have a problem with the white screens though so is hard to fully look and test since crashes on a lot of the pages but progress!

![image](https://user-images.githubusercontent.com/984304/122395733-48712600-cf45-11eb-9be0-5d6ff6014aea.png)

**Comment by Sean-Holcomb** [comment]
Glad to hear that we have addressed one of your issues. Let's see if we can figure out this other one.

1. I would like to see the result of the Asset Api when you reach these white pages, additionally are there any warnings/errors when you run that `/model/etl/asset/rebuild?commit=true`

2. This is handled by reconciliation, these cost are excluded from the OOC costs and are instead used to fill in the adjustment field on your in-cluster costs

**Comment by Sean-Holcomb** [comment]
edit: I spoke with the team and it sounds like we got a fix out this morning. I will let you know if there is another build today but it will be in the nightly tonight.

**Comment by sylus** [comment]
Oh perfect @Sean-Holcomb i'll wait for the nightly and check and if is still a problem will do best to answer your questions.

**Comment by sylus** [comment]
@Sean-Holcomb should I try the nightly now and see if resolves?

**Comment by Sean-Holcomb** [comment]
Yes, I believe the most recent build should solve your issues.

**Comment by sylus** [comment]
@Sean-Holcomb the nightly build seems to not have that error so it looks good so far :D

**Comment by sylus** [comment]
Hey @Sean-Holcomb 

So I wanted to try against fresh data since I was getting some weird numbers but assumed was all the changes.

Therefore I did the following steps:

* scaled down both cost-analyzer and prometheus-server
* deleted the pv claim for both and then recreated
* scaled back up both instances

The Azure Out of Clusters got picked up but then over time in about 5 minutes they disappear which seems odd and I get these errors:

```
E0622 01:12:35.723366 1 log.go:17] [Error] Asset ETL: ComputeAssets: clusterManagementQuery: Prometheus communication error: 400 (Bad Request) URL: 'http://kubecost-prometheus-server.kubecost-system/api/v1/query?query=sum_over_time%28%28avg%28kubecost_cluster_management_cost%29+by+%28cluster_id%29%29%5B-1308m%3A1m%5D%29+%2A+0.016667' Headers: '{ Content-Type: [ application/json ], Date: [ Tue, 22 Jun 2021 01:12:35 GMT ] }', Body: '{"status":"error","errorType":"bad_data","error":"invalid parameter 'query': 1:71: parse error: missing unit character in duration"}' Query: 'sum_over_time((avg(kubecost_cluster_management_cost) by (cluster_id))[-1308m:1m]) * 0.016667': retrying

E0622 01:13:24.726520 1 log.go:17] [Error] Asset ETL: ComputeAssets: clusterManagementQuery: Prometheus communication error: 400 (Bad Request) URL: 'http://kubecost-prometheus-server.kubecost-system/api/v1/query?query=sum_over_time%28%28avg%28kubecost_cluster_management_cost%29+by+%28cluster_id%29%29%5B-1308m%3A1m%5D%29+%2A+0.016667' Headers: '{ Content-Type: [ application/json ], Date: [ Tue, 22 Jun 2021 01:13:24 GMT ] }', Body: '{"status":"error","errorType":"bad_data","error":"invalid parameter 'query': 1:71: parse error: missing unit character in duration"}' Query: 'sum_over_time((avg(kubecost_cluster_management_cost) by (cluster_id))[-1308m:1m]) * 0.016667': retrying
```

> Note: If I run the following command the out of cluster costs will come back for a bit `/model/etl/asset/rebuild?commit=true`

**Comment by Sean-Holcomb** [comment]
I will check it it out and let you know what I find.

**Comment by Sean-Holcomb** [comment]
@sylus can you actually generate a bug report for this one, it sounds like Kubecost is having trouble connecting to Prometheus and that might give us a little bit more insight. Here are the instructions for creating a bug report 
https://github.com/kubecost/docs/blob/master/bug-report.md

**Comment by sylus** [comment]
Thanks @Sean-Holcomb i attached my bug report in the email to support.

I am noticing issues like this where I can click on an item and it keeps opening it up and nesting.

![image](https://user-images.githubusercontent.com/984304/122981369-ab105a80-d367-11eb-862b-66eb46e5e355.png)

**Comment by Sean-Holcomb** [comment]
I got the bug report, thank you

As for that bug you just sent a picture of, we have been tracking that this morning and a fix will be in release 1.82.0, which is going out today.

**Comment by sylus** [comment]
@Sean-Holcomb awesome when that release comes out I will delete my existing deployment and install that one trying everything again :D Thanks so much!

**Comment by sylus** [comment]
Okay @Sean-Holcomb I uninstalled the helm chart and re-installed.

Here is what I have noticed so far:

a) When browsing I see a lot of warnings with the following messages:

```
I0623 14:18:30.674226 1 log.go:32] [Warning] AllocationSet.AggregateBy: error getting share coefficienct for 'cluster-one/__idle__'
I0623 14:18:30.674231 1 log.go:32] [Warning] AllocationSet.AggregateBy: error getting share coefficienct for 'cluster-one/__idle__'
I0623 14:18:30.674236 1 log.go:32] [Warning] AllocationSet.AggregateBy: error getting share coefficienct for 'cluster-one/__idle__'
```

b) My slack notifications and threshold wasn't set again until I manually edited the pricing config map then it got detected and showed up

c) The out of cluster costs hasn't shown up yet but since is a fresh index I think that is because I am still indexing with Prometheus so might have to wait a few hours

I will update this after a few hours with any additional information. :D

**Comment by sylus** [comment]
I think I need to know why when I run `model/etl/asset/rebuild?commit=true` the Azure out of cluster shows up but if I wait a few minutes it disappears again.

**Comment by Sean-Holcomb** [comment]
@sylus rebuilding the assets with that end point `/model/etl/asset/rebuild?commit=true` might have a similar effect. Cloud assets does not populate if there are no in-cluster costs for a window so part of what you are describing is expected. Please let me know if the cloud assets continue to disappear.

**Comment by sylus** [comment]
@Sean-Holcomb I don't understand so I run the ETL clear I then almost immediately see out of cluster costs for lets say the 22nd day but then after about 5 minutes that day disappears and is now just the 23rd and no out of cluster costs listed and it has been about an hour so far and hasn't came back. This honestly doesn't make sense to me.

**Comment by Sean-Holcomb** [comment]
It is sounds like you are saying that initially you are looking at screen where cloud assets are present with the kubernetes service and when you look later you only see the Kubernetes service alone on the page

**Comment by Sean-Holcomb** [comment]
In regards to your other comment about the warning messages
```
I0623 14:18:30.674226 1 log.go:32] [Warning] AllocationSet.AggregateBy: error getting share coefficienct for 'cluster-one/__idle__'
I0623 14:18:30.674231 1 log.go:32] [Warning] AllocationSet.AggregateBy: error getting share coefficienct for 'cluster-one/__idle__'
I0623 14:18:30.674236 1 log.go:32] [Warning] AllocationSet.AggregateBy: error getting share coefficienct for 'cluster-one/__idle__'
```
I can confirm that those can safely be ignored. And I will be making it so that they don't show up soon. Essentially kubecost is distributing shared costs, and it cannot find the proportion to share costs with the 'cluster-one/__idle__' allocation. This is correct though because idle allocations do not receive any shared costs because they are non-allocations that represent unused compute resources.

**Comment by sylus** [comment]
@Sean-Holcomb yup you are correct that is what i am experiencing.

**Comment by Sean-Holcomb** [comment]
Okay I just wanted to make sure that you are actually seeing the kubernetes services alone in the "by service" view and it was not that front end was sending you to "by type" view with a filter for the kubernetes service, which is the default if OOC is not configured. To be honest I am a little confused how the cloud assets are being removed from cache if they are populating.

Are you still seeing 
```
E0622 01:12:35.723366 1 log.go:17] [Error] Asset ETL: ComputeAssets: clusterManagementQuery: Prometheus communication error: 400 (Bad Request) URL: 'http://kubecost-prometheus-server.kubecost-system/api/v1/query?query=sum_over_time%28%28avg%28kubecost_cluster_management_cost%29+by+%28cluster_id%29%29%5B-1308m%3A1m%5D%29+%2A+0.016667' Headers: '{ Content-Type: [ application/json ], Date: [ Tue, 22 Jun 2021 01:12:35 GMT ] }', Body: '{"status":"error","errorType":"bad_data","error":"invalid parameter 'query': 1:71: parse error: missing unit character in duration"}' Query: 'sum_over_time((avg(kubecost_cluster_management_cost) by (cluster_id))[-1308m:1m]) * 0.016667': retrying

E0622 01:13:24.726520 1 log.go:17] [Error] Asset ETL: ComputeAssets: clusterManagementQuery: Prometheus communication error: 400 (Bad Request) URL: 'http://kubecost-prometheus-server.kubecost-system/api/v1/query?query=sum_over_time%28%28avg%28kubecost_cluster_management_cost%29+by+%28cluster_id%29%29%5B-1308m%3A1m%5D%29+%2A+0.016667' Headers: '{ Content-Type: [ application/json ], Date: [ Tue, 22 Jun 2021 01:13:24 GMT ] }', Body: '{"status":"error","errorType":"bad_data","error":"invalid parameter 'query': 1:71: parse error: missing unit character in duration"}' Query: 'sum_over_time((avg(kubecost_cluster_management_cost) by (cluster_id))[-1308m:1m]) * 0.016667': retrying
``` 
since the fresh install?

When you are running the asset rebuild do you see this in the logs?
```
[Info] ETL: Asset: CloudAssets[XXXXX]: run complete; waiting 3 hours for next run
```

**Comment by sylus** [comment]
Hey @Sean-Holcomb I sent you pictures in the support email along with answers to your questions :)

Thanks so much!

**Comment by Sean-Holcomb** [comment]
@sylus That really is strange, can you also confirm that in your step 3 image you have an api request `/model/assets?window=7d&aggregate=service&accumulate=false&req=#####` with no additional parameters?

It sounds like your logs are fine, right now there is either an issue with the query filtering or the cloud assets are somehow being removed from the cache.

**Comment by sylus** [comment]
Yup I confirmed has no additional parameters and yup the logs everything looks fine. What is odd is after 2 days now I see the out of cluster costs but my numbers seem to be off. 

Can this be related to me having some exports that are the same day while i was testing the out of cluster costs? I doubt it is  the guess but am spitballing here ^_^

**Comment by Sean-Holcomb** [comment]
What do you mean by your numbers being off, are you continuing to see the Out of Cluster costs after the weekend?

**Comment by sylus** [comment]
Hey @Sean-Holcomb i am scheduling a meeting to show @AjayTripathy the problem am having. The numbers are orders of magnitude off in the main screen but if you drill down into the assets under kubernetes -> disks they are more accurate.

Once have meeting with @AjayTripathy hopefully I can provide more detailed information.

**Comment by Sean-Holcomb** [comment]
@sylus I made an update that should fix the GPU issue that you are seeing. You can grab the newest in the nightly build

**Comment by sylus** [comment]
Hey @Sean-Holcomb does v1.82.2 have this fix?

**Comment by Sean-Holcomb** [comment]
Yep, looks like it went in the day before that release went out.

**Comment by sylus** [comment]
Hi @Sean-Holcomb did your tagging work? I am running the `gcr.io/kubecost1/cost-model:prod-1.82.2` but the gui says we are 1.82.1 and update is available and GPU fix is not in.

**Comment by Sean-Holcomb** [comment]
@sylus my apologies, it looks like the update is not in v1.82.2, I was able to confirm that it is in the nightly build

**Comment by Sean-Holcomb** [comment]
@sylus just wanted to check that you were able to get this fix up and running. It is in the latest release v1.83.2. Please let me know if you have any other questions here.

**Comment by kirbsauce** [comment]
Hi @sylus , hope things are going well.  Could you let us know if version 1.83.2 (or greater) resolved your issue?  We're here to help!

**Comment by sylus** [comment]
Hi @kirbsauce I sent an email highlighting that sadly OOC is still a problem and reported costs an order of magnitude off. 

I have asked to have a meeting hopefully soon to look over this.

Thx!

**Comment by Sean-Holcomb** [comment]
@sylus Have you seen any improvements since we last spoke? Please let me know if there is anything I can help with.

**Comment by sylus** [comment]
Hey @Sean-Holcomb!

I confirmed today with the latest release 1.86.0 that everything works and out of cluster costs looks to be correct.

Thanks for all of your help and the team itself for getting the remaining issues fixed. ^_^ :)

Much appreciated!
