### ISSUE TITLE
Postgres PVC Template missing

### ISSUE THREAD

**Issue by joerocklin** [kubecost/cost-analyzer-helm-chart#96]
**Describe the bug**
cff5c3983267c8b8e1f65fa318f04c573ecb26ad [introduced a persistent volume claim](https://github.com/kubecost/cost-analyzer-helm-chart/commit/cff5c3983267c8b8e1f65fa318f04c573ecb26ad#diff-9f8637b161126a2155551dac8a0e58d8R40) to the postgres deployment, but there is no associate PVC creation. This blocks the deployment from creating.

**To Reproduce**
1. Deploy the charts with the `remoteWrite.postgres.enabled` set to true

**Expected behavior**
I would expect there to be a PVC template either inline with the deployment or as a separate file in a manner similar to the cost-analyzer PVC template.

**Comment by dwbrown2** [comment]
Hey @joerocklin, thanks for reporting! Just a heads up that this feature today requires an enterprise license. Working with Jeremy now to make progress there.

We should have a fix on the way. Based on what we've seen, the kubecost.com/install path should not be impacted but installing directly from the repo would. Can you confirm what path you are using to install today?

**Comment by joerocklin** [comment]
@dwbrown2 I am installing from the repo

**Comment by dwbrown2** [comment]
Thanks for confirming, fix on the way! Let's discuss this functionality more soon.

**Comment by dwbrown2** [comment]
This was fixed in https://github.com/kubecost/cost-analyzer-helm-chart/pull/97 last night! Please let me know if you run into any other issues.

**Comment by joerocklin** [comment]
I think there's still an issue as the charts sit in the repo. The PVC references a [specific PV](https://github.com/kubecost/cost-analyzer-helm-chart/blob/5af9be9e913cab301e02a6374b5794a20e50941f/cost-analyzer/templates/cost-analyzer-postgres-pvc.yaml#L11) and [storeageClass](https://github.com/kubecost/cost-analyzer-helm-chart/blob/5af9be9e913cab301e02a6374b5794a20e50941f/cost-analyzer/templates/cost-analyzer-postgres-pvc.yaml#L14).

**Comment by AjayTripathy** [comment]
Sorry for the oversight! I appreciate you catching and reporting. Fixed and pushed a new minor version, 1.43.3 -- let me know if we can get you anything else.
